#!/bin/bash

echo "Compilation des fichiers" 
g++ ./MethodeBorda/main.cpp -o ./MethodeBorda/a.out
g++ ./SystemeFrancais/main.cpp -o ./SystemeFrancais/a.out
g++ ./SystemeParNote/main.cpp -o ./SystemeParNote/a.out 
g++ ./SystemeUninominal/main.cpp -o ./SystemeUninominal/a.out

for i in {1..3}
do
	./MethodeBorda/a.out < ./MethodeBorda/FichEntree/MetBordaEntree"$i".txt > ./MethodeBorda/FichSortie/MetBordaSortie"$i".txt
	echo "Methode Borda - Test du fichier oracle $i"
	diff ./MethodeBorda/FichSortie/MetBordaSortie"$i".txt ./MethodeBorda/FichOracle/BordaOracle"$i".txt
done

echo 

for i in {1..3}
do
	./SystemeFrancais/a.out < ./SystemeFrancais/FichEntree/SystemeFrancaisEntree"$i".txt > ./SystemeFrancais/FichSortie/SystemeFrancaisSortie"$i".txt
	echo "Systeme Francais - Test du fichier oracle $i"
	diff ./SystemeFrancais/FichSortie/SystemeFrancaisSortie"$i".txt ./SystemeFrancais/FichOracle/FrancaisOracle"$i".txt
done

echo 

for i in {1..3}
do
	./SystemeParNote/a.out < ./SystemeParNote/FichEntree/SysNoteEntree"$i".txt > ./SystemeParNote/FichSortie/SysNoteSortie"$i".txt
	echo "Systeme par Note - Test du fichier oracle $i"
	diff ./SystemeParNote/FichSortie/SysNoteSortie"$i".txt ./SystemeParNote/FichOracle/SysNoteOracle"$i".txt
done

echo 

for i in {1..3}
do
	./SystemeUninominal/a.out < ./SystemeUninominal/FichEntree/UninominalEntree"$i".txt > ./SystemeUninominal/FichSortie/UninominalSortie"$i".txt
	echo "Systeme Uninominal - Test du fichier oracle $i"
	diff ./SystemeUninominal/FichSortie/UninominalSortie"$i".txt ./SystemeUninominal/FichOracle/UninominalOracle"$i".txt
done
